font_family JetBrainsMono Nerd Font
font_size 13.0

background_opacity 0.78
window_padding_width 12

cursor_shape beam
cursor_blink_interval 0.5

confirm_os_window_close 0
hide_window_decorations yes

enable_audio_bell no
shell_integration enabled

foreground              #D3C6AA
background              #232A2E

selection_foreground    #232A2E
selection_background    #D3C6AA

cursor                  #A7C080
cursor_text_color       #232A2E

active_tab_foreground   #D3C6AA
active_tab_background   #374145
inactive_tab_foreground #859289
inactive_tab_background #2D353B

color0  #414B50
color1  #E67E80
color2  #A7C080
color3  #DBBC7F
color4  #7FBBB3
color5  #D699B6
color6  #83C092
color7  #D3C6AA

color8  #475258
color9  #E67E80
color10 #A7C080
color11 #DBBC7F
color12 #7FBBB3
color13 #D699B6
color14 #83C092
color15 #D3C6AA
